### ISSUE TITLE
ethercat_hardware package doesn't build currently

### ISSUE THREAD

**Issue by toliver** [PR2/pr2_ethercat_drivers#62]
When building ros from source (I'm doing it in a Raspberry Pi, but the same thing happens if you build it in an AMD64 PC) motorconf.cpp won't compile. The error is probably due to recent changes in the rosconsole package.

```
/code/hydro/test_catkin_ws/src/pr2_ethercat_drivers/ethercat_hardware/src/motorconf.cpp: In function ‘int main(int, char**)’:
/code/hydro/test_catkin_ws/src/pr2_ethercat_drivers/ethercat_hardware/src/motorconf.cpp:642:3: error: ‘log4cxx’ has not been declared
/code/hydro/test_catkin_ws/src/pr2_ethercat_drivers/ethercat_hardware/src/motorconf.cpp:642:22: error: expected ‘;’ before ‘logger’
/code/hydro/test_catkin_ws/src/pr2_ethercat_drivers/ethercat_hardware/src/motorconf.cpp:643:3: error: ‘logger’ was not declared in this scope
/code/hydro/test_catkin_ws/src/pr2_ethercat_drivers/ethercat_hardware/src/motorconf.cpp:643:20: error: ‘g_level_lookup’ is not a member of ‘ros::console’
make[2]: *** [pr2_ethercat_drivers/ethercat_hardware/CMakeFiles/motorconf.dir/src/motorconf.cpp.o] Error 1
```

**Comment by ahendrix** [comment]
Thanks for the heads-up!

You are correct; this is due to a recent change in the ros_comm and roscpp_core stacks to remove a dependency on log4cxx. I'm going to reach out to the core ROS team to see if they have a recommendation on how to resolve this.

**Comment by ahendrix** [comment]
I've asked for a general recommendation about this on ROS answers: http://answers.ros.org/question/116436/missing-log4cxx-on-latest-ros_comm/

**Comment by dirk-thomas** [comment]
The code should depend and include log4cxx explicitly when using it itself. Relying on transitive dependencies is not stable and by no means guaranteed.

You might also consider the function used by the get/set logger level RPC: `ros::console::set_logger_level(...)` But you have to explicitly invoke `ros::console::notifyLoggerLevelsChanged()` when logger levels have been successfully set in order for them to be applied.

**Comment by trainman419** [comment]
I may have to revert this fix, pending discussion on http://answers.ros.org/question/116436/missing-log4cxx-on-latest-ros_comm/

**Comment by dirk-thomas** [comment]
Please address the missing explicit dependency on log4cxx to unbreak the build on the farm.
