### ISSUE TITLE
Missing executable flag of finger_tip pressure's scripts

### ISSUE THREAD

**Issue by YuOhara** [PR2/pr2_ethercat_drivers#67]
I installed finger_tip_pressure programs by apt-get.
But I can't exec it because executable flag is not set.

``` sh
applications@pr1012:/opt/ros/hydro/lib/fingertip_pressure$ ls -l
total 32
-rw-r--r-- 1 root root 2369 Feb 27  2014 plot_pressure.pl
-rw-r--r-- 1 root root 5676 Feb 27  2014 rectangle_viz.py
-rw-r--r-- 1 root root 3016 Feb 27  2014 sensor_info.py
-rw-r--r-- 1 root root 3227 Feb 27  2014 sim_sensor.py
-rw-r--r-- 1 root root 6568 Feb 27  2014 sphere_viz.py
-rw-r--r-- 1 root root 3507 Feb 27  2014 view_fingertip_pressure
```

cc @garaemon

**Comment by garaemon** [comment]
It's fixed by https://github.com/PR2/pr2_ethercat_drivers/commit/2428a9efb862147d826c97c60ba43cbca4f63777, and it's not relased yet.

**Comment by UltronDestroyer** [comment]
Needs a re-release?

**Comment by garaemon** [comment]
Yes, could you release a new version as apt package?

2014年9月29日月曜日、Devon Ashnotifications@github.comさんは書きました:

> Needs a re-release?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PR2/pr2_ethercat_drivers/issues/67#issuecomment-57159759
> .

## 

from iPhone

**Comment by UltronDestroyer** [comment]
Hm, I'm having some difficulty re-releasing it.

**Comment by UltronDestroyer** [comment]
I've just released it. It should be made available soon

**Comment by UltronDestroyer** [comment]
I've just released it. It should be made available soon
